/*
 * Copyright (C) 2017 Dennis Neufeld
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package space.npstr.wolfia.db.entity.stats;

import space.npstr.wolfia.game.definitions.Roles;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Created by napster on 30.05.17.
 * <p>
 * Describe a participant of a game
 */
@Entity
@Table(name = "stats_player")
public class PlayerStats implements Serializable {

    private static final long serialVersionUID = -4581124627322215168L;

    //dont really care about this one, its for the database
    @Id
    @Column(name = "player_id")
    @GeneratedValue
    private long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "team_id")
    private TeamStats team;

    @Column(name = "user_id")
    private long userId;

    //nickname on the guild where the main channel of the game is
    @Column(name = "nickname")
    private String nickname;

    //defined in the Roles enum
    @Column(name = "role")
    private String role;

    @Column(name = "total_posts")
    private int totalPosts;

    @Column(name = "total_postlength")
    private int totalPostLength;

    public PlayerStats(final TeamStats team, final long userId, final String nick, final Roles role) {
        this.team = team;
        this.userId = userId;
        this.nickname = nick;
        this.role = role.name();
        this.totalPosts = 0;
        this.totalPostLength = 0;
    }

    public synchronized void bumpPosts(final int length) {
        this.totalPosts++;
        this.totalPostLength += length;
    }

    //do not use the autogenerated id, it will only be set after persisting
    @Override
    public int hashCode() {
        final int prime = 31;
        //todo test if referencing team here produces any kind of errors, since it's marked as lazy loading
        int result = this.team.hashCode();
        result = prime * result + (int) (this.userId ^ (this.userId >>> 32));
        return result;
    }

    //do not compare the autogenerated id, it will only be set after persisting
    @Override
    public boolean equals(final Object obj) {
        if (!(obj instanceof PlayerStats)) {
            return false;
        }
        final PlayerStats p = (PlayerStats) obj;
        //todo test if referencing team here produces any kind of errors, since it's marked as lazy loading
        return this.userId == p.userId && this.team.equals(p.team);
    }

    //########## boilerplate code below

    PlayerStats() {
    }

    public long getId() {
        return this.id;
    }

    public void setId(final long id) {
        this.id = id;
    }

    public TeamStats getTeam() {
        return this.team;
    }

    public void setTeam(final TeamStats team) {
        this.team = team;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(final long userId) {
        this.userId = userId;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(final String nickname) {
        this.nickname = nickname;
    }

    public Roles getRole() {
        return Roles.valueOf(this.role);
    }

    public void setRole(final Roles role) {
        this.role = role.name();
    }

    public int getTotalPosts() {
        return this.totalPosts;
    }

    public void setTotalPosts(final int totalPosts) {
        this.totalPosts = totalPosts;
    }

    public int getTotalPostLength() {
        return this.totalPostLength;
    }

    public void setTotalPostLength(final int totalPostLength) {
        this.totalPostLength = totalPostLength;
    }
}
