# Required services to run Wolfia on a local machine

services:
  db:
    image: napstr/poggres:18
    restart: always
    ports:
      - 127.0.0.1:5442:5432
    volumes:
      - ./postgres-data/:/var/lib/postgresql/
    environment:
      - POSTGRES_PASSWORD=wolfia
      - ROLE=wolfia
      - PASSWORD=wolfia
      - DB=wolfia
      - EXTENSIONS=hstore
