---

wolfia:
  discordToken:            ""     # Discord bot token. From Discord's Developer console: https://discord.com/developers/applications. Make sure to enable the Server Members intent: https://cdn.discordapp.com/attachments/439855192763269135/816787436440911872/unknown.png
  #botstatus-webhook:       ""     # Webhook url to post the bot status in. Optional.

oauth2:
  clientId:                ""     # From Discord's Developer console: https://discord.com/developers/applications
  clientSecret:            ""     # From Discord's Developer console: https://discord.com/developers/applications
  #baseRedirectUrl:         "https://xyz.lhr.life" # During development, put in your ngrok/localhost.run subdomain and uncomment instead of line above.

sentry.dsn:                ""     # Error aggregation service. See https://sentry.io

spring:
  #datasource.url:          ""     # Postgres database url. Only needs to be set when NOT running with the docker/dev/compose file.
  #data.redis.url:          ""     # Redis database url. Only needs to be set when NOT running with the docker/dev/compose file.
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id:     ""      # From Discord's Developer console: https://discord.com/developers/applications
            #redirect-uri:  "https://xyz.lhr.life/login/oauth2/code/discord" # During development, put in your ngrok/localhost.run subdomain and uncomment.
