---

wolfia:
  discordToken:            ""     # Discord bot token. From Discord's Developer console: https://discord.com/developers/applications

#database.jdbcUrl:          ""     # Postgres database url. Only needs to be set when NOT running with the docker/dev/docker-compose file.

oauth2:
  clientId:                ""     # From Discord's Developer console: https://discord.com/developers/applications
  clientSecret:            ""     # From Discord's Developer console: https://discord.com/developers/applications
  #baseRedirectUrl:         "https://xyz.ngrok.io" # During development, put in your ngrok subdomain and uncomment instead of line above.

sentry.dsn:                ""     # Error aggregation service. See https://sentry.io

spring:
  #redis.url:               ""     # Redis database url. Only needs to be set when NOT running with the docker/dev/docker-compose file.
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id:     ""      # From Discord's Developer console: https://discord.com/developers/applications
            client-secret: ""      # From Discord's Developer console: https://discord.com/developers/applications
            #redirect-uri:  "https://xyz.ngrok.io/login/oauth2/code/discord" # During development, put in your ngrok subdomain and uncomment.
