networks:
  dockersock4traefik:
  wolfia_default:
    external: true

services:

  # https://github.com/Tecnativa/docker-socket-proxy
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    container_name: dockerproxy
    restart: always
    environment:
      CONTAINERS: 1
    ports:
      - 2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:z"
    networks:
      - dockersock4traefik

  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    networks:
      - default
      - dockersock4traefik
      - wolfia_default
    volumes:
      - ./acme.json:/acme.json:rw
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.http.middlewares.metrics-auth.basicauth.users=${METRICS_LOGIN}"
      - "traefik.http.middlewares.metrics-auth.basicauth.removeheader=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASH_LOGIN}"
      - "traefik.http.middlewares.whitelist.ipallowlist.sourcerange=${CF_WHITELIST}"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=traefik-auth@docker, whitelist@docker"
    command:
      - "--log.level=info"
      - "--accesslog=true"
      - "--global.sendanonymoususage=true"
      - "--entrypoints.https.address=:443"
      - "--api.dashboard=true"
      - "--api.debug=false"
      - "--providers.docker.endpoint=tcp://dockerproxy:2375"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
    environment:
      - CF_API_EMAIL=${CF_MAIL}
      - CF_API_KEY=${CF_KEY}
