FROM arm64v8/openjdk:11-jdk-slim
MAINTAINER napster@npstr.space

ENV ENV docker

WORKDIR /opt/wolfia

COPY build/libs/wolfia.jar /opt/wolfia/wolfia.jar

EXPOSE 4567

ENTRYPOINT ["java", "-jar", "-Xmx512m", "wolfia.jar"]
