/*
 * Copyright (C) 2016-2023 the original author or authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package space.npstr.wolfia.domain.stats;

import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import space.npstr.wolfia.game.definitions.Games;

import static space.npstr.wolfia.game.GameInfo.GameMode;

/**
 * Describe a game that happened
 */
public class InsertGameStats {

    private final Set<InsertTeamStats> startingTeams = new HashSet<>();
    private final Set<InsertActionStats> actions = new HashSet<>();
    private final long startTime;
    private long endTime;
    private final long guildId;
    private final String guildName;
    private final long channelId;
    private final String channelName;
    private final Games gameType;
    private final GameMode gameMode;
    private final int playerSize;


    public InsertGameStats(long guildId, String guildName, long channelId, String channelName, Games gameType,
                           GameMode gameMode, int playerSize) {

        this.guildId = guildId;
        this.guildName = guildName;
        this.channelId = channelId;
        this.channelName = channelName;
        this.startTime = System.currentTimeMillis();
        this.gameType = gameType;
        this.gameMode = gameMode;
        this.playerSize = playerSize;
    }

    public void addAction(InsertActionStats action) {
        this.actions.add(action);
    }

    public void addActions(Collection<InsertActionStats> actions) {
        this.actions.addAll(actions);
    }

    public void setActions(Collection<InsertActionStats> actions) {
        this.actions.clear();
        this.actions.addAll(actions);
    }

    public void addTeam(InsertTeamStats team) {
        this.startingTeams.add(team);
    }

    public void setTeams(Collection<InsertTeamStats> teams) {
        this.startingTeams.clear();
        this.startingTeams.addAll(teams);
    }

    //do not use the autogenerated id, it will only be set after persisting
    @Override
    public int hashCode() {
        int prime = 31;
        int result = 1;
        result = prime * result + (int) (this.guildId ^ (this.guildId >>> 32));
        result = prime * result + (int) (this.channelId ^ (this.channelId >>> 32));
        result = prime * result + (int) (this.startTime ^ (this.startTime >>> 32));
        return result;
    }

    //do not compare the autogenerated id, it will only be set after persisting
    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof InsertGameStats)) {
            return false;
        }
        InsertGameStats g = (InsertGameStats) obj;
        return this.startTime == g.startTime && this.guildId == g.guildId && this.channelId == g.channelId;
    }

    public Set<InsertTeamStats> getStartingTeams() {
        return Collections.unmodifiableSet(this.startingTeams);
    }

    public Set<InsertActionStats> getActions() {
        return Collections.unmodifiableSet(this.actions);
    }

    public long getStartTime() {
        return this.startTime;
    }

    public long getEndTime() {
        return this.endTime;
    }

    public void setEndTime(long endTime) {
        this.endTime = endTime;
    }

    public long getGuildId() {
        return this.guildId;
    }

    public String getGuildName() {
        return this.guildName;
    }

    public long getChannelId() {
        return this.channelId;
    }

    public String getChannelName() {
        return this.channelName;
    }

    public Games getGameType() {
        return this.gameType;
    }

    public GameMode getGameMode() {
        return this.gameMode;
    }

    public int getPlayerSize() {
        return this.playerSize;
    }

}
