/*
 * Copyright (C) 2016-2019 Dennis Neufeld
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package space.npstr.wolfia.domain.stats;

import space.npstr.wolfia.game.definitions.Alignments;

import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;

/**
 * Created by napster on 01.06.17.
 * <p>
 * model of a team in a game
 */
public class TeamStats {

    private Optional<Long> teamId = Optional.empty();

    private final GameStats game;

    private final Set<PlayerStats> players = new HashSet<>();

    private final Alignments alignment;

    //watch out: teams of the same alignment (example: wolves) may not have the same name, or the equals function will
    //go haywire
    private final String name;

    private boolean isWinner = false;

    private int teamSize;


    public TeamStats(GameStats game, Alignments alignment, String name, int teamSize) {
        this.game = game;
        this.alignment = alignment;
        this.name = name;
        this.teamSize = teamSize;
    }

    // for use by the stats repository
    public TeamStats(long teamId, String alignment, boolean isWinner, String name, GameStats gameStats, int teamSize) {
        this.teamId = Optional.of(teamId);
        this.alignment = Alignments.valueOf(alignment);
        this.isWinner = isWinner;
        this.name = name;
        this.game = gameStats;
        this.teamSize = teamSize;
    }

    public void addPlayer(final PlayerStats player) {
        this.players.add(player);
    }

    public void setPlayers(final Collection<PlayerStats> players) {
        this.players.clear();
        this.players.addAll(players);
    }


    //do not use the autogenerated id, it will only be set after persisting
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = this.game.hashCode();
        result = prime * result + this.alignment.hashCode();
        result = prime * result + this.name.hashCode();
        return result;
    }

    //do not compare the autogenerated id, it will only be set after persisting
    @Override
    public boolean equals(final Object obj) {
        if (!(obj instanceof TeamStats)) {
            return false;
        }
        final TeamStats t = (TeamStats) obj;
        return this.game.equals(t.game) && this.alignment.equals(t.alignment) && this.name.equals(t.name);
    }


    public Optional<Long> getTeamId() {
        return this.teamId;
    }

    public void setTeamId(long teamId) {
        this.teamId = Optional.of(teamId);
    }

    public GameStats getGame() {
        return this.game;
    }

    public Set<PlayerStats> getPlayers() {
        return Collections.unmodifiableSet(this.players);
    }

    public Alignments getAlignment() {
        return this.alignment;
    }

    public String getName() {
        return this.name;
    }

    public boolean isWinner() {
        return this.isWinner;
    }

    public void setWinner(final boolean winner) {
        this.isWinner = winner;
    }

    public int getTeamSize() {
        return this.teamSize;
    }

    public void setTeamSize(final int teamSize) {
        this.teamSize = teamSize;
    }
}
